### ISSUE TITLE
Quit not working when no file is opened

### ISSUE THREAD

**Issue by delightfulagony** [LonnyGomes/hexcurse#41] opened 2022-02-17 16:11 UTC
Whenever hexcurse is opened without passing a file to it the `C-q` shortcut doesn't work.

## Steps to reproduce
1. Open hexcurse without passing any file
    $ `hexcurse`
2. When pressing `C-q` it doesn't close

If you open a file and then press `C-q` it works normally

## Host info
OS: Gentoo Linux (5.15.16-gentoo-x86_64)
Version: 1.60.0 (https://packages.gentoo.org/packages/app-editors/hexcurse)

**Comment by prso** [comment] 2022-02-27 02:37
Duplicate of #23.
Fixed in https://github.com/LonnyGomes/hexcurse/commit/37f94f2c1d0a3cc5110b2771e02ed894522d65d3.

Unfortunately this was after version 1.60.0

**Comment by prso** [comment] 2022-02-27 02:41
I recommend my [fork](https://github.com/prso/hexcurse) that includes this and many other improvements and fixes.

**Comment by polluks** [comment] 2022-03-08 20:10
Here comes the lost screenshot in the README.md
![hexcurse screenshot](https://web.archive.org/web/20180308070733/http://lonnygomes.github.io/screenshots/hexcurse2-ss.jpg)

**Closed as completed** 2022-06-12 11:20 UTC
